#!/bin/bash

# Copyright 2023 Radio New Japan.
# 
# Redistribution and use in source and binary forms, with or without modification, are permitted
# provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions
#    and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions
#    and the following disclaimer in the documentation and/or other materials provided with the distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or
#    promote products derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
# OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e
set -o pipefail
set -u

export LC_ALL=C

PROFILE_DIR=$1
if [ ! -f ${PROFILE_DIR}/profiledef.sh ]; then
	echo "ERROR: No profile specified!"
	echo "usage: sudo ./mkdebiso <profile directory>"
	exit 1
fi

DISTRO_NAME=""
DISTRO_UNAME=""
DISTRO_VERSION=""
UPSTREAM=""
UPSTREAM_VERSION=""
MIRROR_URL=""
ARCH=""

source "${PROFILE_DIR}/profiledef.sh"

_user_distinction(){
	if [[ $(whoami) != "root" ]]; then
		echo "ERROR: Need to run as root!"
		exit 1
	elif [[ ${ARCH} != "amd64" ]]; then
		echo "ERROR: Selected architecture not supported!"
		exit 1
	fi
}

_prepare(){
	mkdir -p work/chroot

	debootstrap --arch=${ARCH} --variant=minbase ${UPSTREAM_VERSION} work/chroot ${MIRROR_URL}

	cp -pr 	${PROFILE_DIR}/dirootfs/* work/chroot/
	cp -p ${PROFILE_DIR}/packages.${ARCH} work/
	sed "/^\#/d" -i work/packages.${ARCH}
	cp -pr ${PROFILE_DIR}/grub work/
	cp -pr ${PROFILE_DIR}/sources.list work/chroot/etc/apt/
	if [ -d ${PROFILE_DIR}/calamares-config.d ]; then
		cp -pr ${PROFILE_DIR}/calamares-config.d/* work/chroot/
	fi
	if [ -d ${PROFILE_DIR}/sources.list.d ]; then
		cp -pr ${PROFILE_DIR}/sources.list.d/* work/chroot/etc/apt/sources.list.d/
	fi
	if [ -d ${PROFILE_DIR}/trusted.gpg.d ]; then
		cp -pr ${PROFILE_DIR}/trusted.gpg.d/* work/chroot/etc/apt/trusted.gpg.d/
	fi
	if [ -f ${PROFILE_DIR}/exclude_packages.${ARCH} ]; then
		cp -p ${PROFILE_DIR}/exclude_packages.${ARCH} work/
		sed /^\#/d -i work/exclude_packages.${ARCH}
	fi
	if [ -f ${PROFILE_DIR}/flatpak_packages.${ARCH} ]; then
		cp -p ${PROFILE_DIR}/flatpak_packages.${ARCH} work/
	 sed /^\#/d -i work/flatpak_packages.${ARCH}
	fi
	if [ -f ${PROFILE_DIR}/ppa.${ARCH} ]; then
		cp -p ${PROFILE_DIR}/ppa.${ARCH} work/
		sed "/^\#/d" -i work/ppa.${ARCH}
	fi
	if [ -d work/chroot/root/customise_dirootfs.d/ ]; then
		chmod 755 work/chroot/root/customise_dirootfs.d/*.sh
	fi

	sed "s/%DISTRO_UNAME%/${DISTRO_NAME}/g" -i work/grub/grub.cfg
	sed "s/%DISTRO_UNAME%/${DISTRO_UNAME}/g" -i work/grub/grub.cfg

	# chroot
	cd work
	mount --bind /dev chroot/dev
	mount --bind /run chroot/run
	chroot chroot mount none -t proc /proc
	chroot chroot mount none -t sysfs /sys
	chroot chroot mount none -t devpts /dev/pts
}

_setup(){
	chmod 700 chroot/root
	chown root:root chroot/root

	if [ -f ppa.${ARCH} ]; then
		chroot chroot apt-get install -y software-properties-common
		PPALIST=($(cat ppa.${ARCH}))
		for ((i=0; i < ${#PPALIST[*]}; i++)); do
			chroot chroot add-apt-repository -y ppa:${PPALIST[i]}
		done
	fi

	if [ -f chroot/root/customise_dirootfs.d/preinstall.sh ]; then
		chroot chroot /root/customise_dirootfs.d/preinstall.sh
	fi

	chroot chroot apt-get update
	chroot chroot apt-get upgrade -y
	chroot chroot apt-get install -y $(cat packages.${ARCH})

	if [ -f chroot/root/customise_dirootfs.d/postinstall.sh ]; then
		chroot chroot /root/customise_dirootfs.d/postinstall.sh
	fi

	if [ -f exclude_packages.${ARCH} ]; then
		chroot chroot apt-get purge -y --autoremove $(cat exclude_packages.${ARCH})
	fi

	# flatpak's pkgs
	if [ -f flatpak_packages.${ARCH} ]; then
		chroot chroot apt-get install -y flatpak
		chroot chroot flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
		chroot chroot flatpak update
		chroot chroot flatpak install -y flathub $(cat flatpak_packages.${ARCH})
	fi

	_PATH="$(chroot /var/lib/machines/debian printenv PATH):/usr/sbin"

	PATH=${_PATH} chroot chroot /usr/sbin/dpkg-reconfigure locales
	PATH=${_PATH} chroot chroot /usr/sbin/dpkg-reconfigure resolvconf

	cat <<EOF > chroot/etc/NetworkManager/NetworkManager.conf
[main]
rc-manager=resolvconf
plugins=ifupdown,keyfile
dns=dnsmasq

[ifupdown]
managed=false
EOF
	PATH=${_PATH} chroot chroot /usr/sbin/dpkg-reconfigure network-manager

	chroot chroot apt-get clean -y
}

_build_iso(){
	umount -l chroot/proc
	umount -l chroot/sys
	umount -l chroot/dev/pts
	umount -l chroot/dev
	umount -l chroot/run

	if [[ ${UPSTREAM} == "debian" ]]; then
		LIVEDIR=live
	elif [[ ${UPSTREAM} == "ubuntu" ]]; then
		LIVEDIR=casper
	fi

	mkdir iso
	mkdir -p iso/{${LIVEDIR},isolinux,install}

	# copy memtest86
	if [[ ${UPSTREAM} == "debian" ]]; then
		cp chroot/boot/memtest86+x64.bin iso/install/memtest86+
	elif [[ ${UPSTREAM} == "ubuntu" ]]; then
		cp chroot/boot/memtest86+.bin iso/install/memtest86+
	fi

	wget https://www.memtest86.com/downloads/memtest86-usb.zip -O iso/install/memtest86-usb.zip
	unzip -p iso/install/memtest86-usb.zip memtest86-usb.img > iso/install/memtest86
	rm -f iso/install/memtest86-usb.zip

	# copy kernel
	if [[ ${UPSTREAM} == "debian" ]]; then
			cp chroot/boot/vmlinuz-**-**-${ARCH} iso/live/vmlinuz
			cp chroot/boot/initrd.img-**-**-${ARCH} iso/live/initrd
	elif [[ ${UPSTREAM} == "ubuntu" ]]; then
			cp chroot/boot/vmlinuz-**-**-generic iso/casper/vmlinuz
			cp chroot/boot/initrd.img-**-**-generic iso/casper/initrd
	fi

	# grub
	touch iso/${DISTRO_UNAME}
	cp grub/grub.cfg iso/isolinux/grub.cfg

	# package list
	chroot chroot dpkg-query -W --showformat='${Package} ${Version}\n' > iso/${LIVEDIR}/filesystem.packages

	# compress rootfs
	mksquashfs chroot iso/${LIVEDIR}/filesystem.squashfs \
	    -noappend -no-duplicates -no-recovery \
	    -wildcards \
	    -e "var/cache/apt/archives/*" \
	    -e "root/*" \
	    -e "root/.*" \
	    -e "tmp/*" \
	    -e "tmp/.*" \
	    -e "swapfile"

	# generate iso
	pushd iso
	grub-mkstandalone \
	    --format=x86_64-efi \
	    --output=isolinux/bootx64.efi \
	    --locales="" \
	    --fonts="" \
	    "boot/grub/grub.cfg=isolinux/grub.cfg"

	grub-mkstandalone \
	    --format=i386-efi \
	    --output=isolinux/bootia32.efi \
	    --locales="" \
	    --fonts="" \
	    "boot/grub/grub.cfg=isolinux/grub.cfg"

	(
        cd isolinux && \
        dd if=/dev/zero of=efiboot.img bs=1M count=20 && \
        mkfs.vfat efiboot.img && \
        LC_CTYPE=C mmd -i efiboot.img efi efi/boot && \
        LC_CTYPE=C mcopy -i efiboot.img ./bootia32.efi ::efi/boot/ && \
        LC_CTYPE=C mcopy -i efiboot.img ./bootx64.efi ::efi/boot/
	)

	grub-mkstandalone \
        --format=i386-pc \
        --output=isolinux/core.img \
        --install-modules="linux16 linux normal iso9660 biosdisk memdisk search tar ls" \
        --modules="linux16 linux normal iso9660 biosdisk search" \
        --locales="" \
        --fonts="" \
        --themes="" \
        "boot/grub/grub.cfg=isolinux/grub.cfg"

	cat /usr/lib/grub/i386-pc/cdboot.img isolinux/core.img > isolinux/bios.img

	/bin/bash -c "(find . -type f -print0 | xargs -0 md5sum | grep -v -e 'md5sum.txt' -e 'bios.img' -e 'efiboot.img' > md5sum.txt)"

	# build iso
	mkdir ../../out

	xorriso \
	    -as mkisofs \
	    -iso-level 3 \
	    -full-iso9660-filenames \
	    -volid "${DISTRO_UNAME}" \
	    -eltorito-boot boot/grub/bios.img \
	    -no-emul-boot \
	    -boot-load-size 4 \
	    -boot-info-table \
	    --eltorito-catalog boot/grub/boot.cat \
	    --grub2-boot-info \
	    --grub2-mbr /usr/lib/grub/i386-pc/boot_hybrid.img \
	    -eltorito-alt-boot \
	    -e EFI/efiboot.img \
	    -no-emul-boot \
	    -append_partition 2 0xef isolinux/efiboot.img \
	    -output "../../out/${DISTRO_UNAME}-${DISTRO_VERSION}-${ARCH}.iso" \
	    -m "isolinux/efiboot.img" \
	    -m "isolinux/bios.img" \
	    -graft-points \
	       "/EFI/efiboot.img=isolinux/efiboot.img" \
	       "/boot/grub/bios.img=isolinux/bios.img" \
	       "."

	popd
}

_user_distinction
_prepare
_setup
_build_iso

export LC_ALL=$(printenv LANG)
exit 0
